### ISSUE TITLE
Is there a way to write a test that expects 0 rows to be returned?

### ISSUE THREAD

**Issue by jamoore5** [EqualExperts/dbt-unit-testing#140] opened 2023-05-04 13:36 UTC
I stumbled onto this package when trying to figure out how to write some unit test in a dbt project. 

It has meant most of my needs but I am wondering if I have missed how to test with the expectation that new rows are returned?

**Comment by the-serious-programmer** [comment] 2023-05-12 12:17
Seems a duplicate of: https://github.com/EqualExperts/dbt-unit-testing/issues/93

**Closed** 2023-05-12 13:25 UTC
